import {
  AlarmIcon,
  BellIcon,
  BellSimpleIcon,
  BellSimpleRingingIcon,
  BirdIcon,
  CaretDoubleDownIcon,
  ChartLineUpIcon,
  ChatsCircleIcon,
  CrosshairIcon,
  DotOutlineIcon,
  DotsThreeOutlineIcon,
  FireIcon,
  HeartbeatIcon,
  LightningIcon,
  MegaphoneIcon,
  MetronomeIcon,
  MusicNotesIcon,
  PoliceCarIcon,
  PulseIcon,
  RepeatIcon,
  SirenIcon,
  SnowflakeIcon,
  SparkleIcon,
  StepsIcon,
  TimerIcon,
  TrendDownIcon,
  TrendUpIcon,
  WaveSawtoothIcon,
  WaveSineIcon,
  WaveSquareIcon,
  WaveTriangleIcon,
  type Icon,
} from '@phosphor-icons/react';

import * as storage from '@/lib/storage';

const KEY = 'dynavolt.alertSound';

export type AlertSoundName =
  | 'default'
  | 'chirp'
  | 'alarm'
  | 'beep'
  | 'sweep'
  | 'pulse'
  | 'siren'
  | 'warble'
  | 'ping'
  | 'tritone'
  | 'descend'
  | 'klaxon'
  | 'trill'
  | 'strobe'
  | 'bell'
  | 'surge'
  | 'blip'
  | 'buzzer'
  | 'chatter'
  | 'chime'
  | 'dive'
  | 'drone'
  | 'echo'
  | 'glass'
  | 'heartbeat'
  | 'ladder'
  | 'march'
  | 'radar'
  | 'spark'
  | 'tick'
  | 'whoop';

/**
 * The alert tones that ship inside the app.
 *
 * Bundled rather than picked at runtime, because that is the only kind of sound Android
 * will play for a notification while the app is closed. A channel's sound is copied
 * from the app's resources when the channel is created, so the file has to exist at
 * install time; a file chosen later cannot take its place.
 *
 * The files live in public/sounds, which the page plays from, and are copied into the
 * Android project's res/raw by scripts/copy-android-sounds.mjs, which the channels
 * read from.
 *
 * Generated by `scripts/build-alert-sounds.mjs`. They sit between roughly 1 and 3 kHz,
 * which is where a phone speaker is loudest and where a tone still carries across a
 * room with a transformer humming in it.
 *
 * Each one needs its own channel: Android freezes a channel's sound at creation, so
 * switching tones means switching channels rather than editing one.
 *
 * Listed alphabetically, with the device default pinned first: it is the "no chosen
 * tone" option rather than a tone, so it belongs at the top rather than filed under D.
 */
export const ALERT_SOUNDS: {
  value: AlertSoundName;
  label: string;
  description: string;
  /** The channel this tone plays through, or the shared default one. */
  channelId: string;
  /** The bundled file name, or null for Android's own notification sound. */
  file: string | null;
  /** The bundled file's URL, for playing while the app is open. */
  asset: string | null;
  icon: Icon;
}[] = [
  {
    value: 'default',
    label: 'Device default',
    description: 'The notification sound your phone already uses.',
    channelId: 'alerts-v2',
    file: null,
    asset: null,
    icon: BellIcon,
  },


  {
    value: 'alarm',
    label: 'Alarm',
    description: 'Two tones back and forth, like an emergency vehicle.',
    channelId: 'alerts-alarm-v1',
    file: 'alarm.wav',
    asset: '/sounds/alarm.wav',
    icon: AlarmIcon,
  },


  {
    value: 'beep',
    label: 'Beep',
    description: 'Three plain high beeps.',
    channelId: 'alerts-beep-v1',
    file: 'beep.wav',
    asset: '/sounds/beep.wav',
    icon: DotsThreeOutlineIcon,
  },


  {
    value: 'bell',
    label: 'Bell',
    description: 'A bell that rings out slowly.',
    channelId: 'alerts-bell-v1',
    file: 'bell.wav',
    asset: '/sounds/bell.wav',
    icon: BellSimpleRingingIcon,
  },

  {
    value: 'blip',
    label: 'Blip',
    description: 'A single quick tick.',
    channelId: 'alerts-blip-v1',
    file: 'blip.wav',
    asset: '/sounds/blip.wav',
    icon: DotOutlineIcon,
  },

  {
    value: 'buzzer',
    label: 'Buzzer',
    description: 'A harsh low buzz.',
    channelId: 'alerts-buzzer-v1',
    file: 'buzzer.wav',
    asset: '/sounds/buzzer.wav',
    icon: WaveSquareIcon,
  },

  {
    value: 'chatter',
    label: 'Chatter',
    description: 'Fast little tones, one after another.',
    channelId: 'alerts-chatter-v1',
    file: 'chatter.wav',
    asset: '/sounds/chatter.wav',
    icon: ChatsCircleIcon,
  },

  {
    value: 'chime',
    label: 'Chime',
    description: 'Two notes, like a doorbell.',
    channelId: 'alerts-chime-v1',
    file: 'chime.wav',
    asset: '/sounds/chime.wav',
    icon: BellSimpleIcon,
  },


  {
    value: 'chirp',
    label: 'Chirp',
    description: 'Two quick rising notes.',
    channelId: 'alerts-chirp-v1',
    file: 'chirp.wav',
    asset: '/sounds/chirp.wav',
    icon: BirdIcon,
  },


  {
    value: 'descend',
    label: 'Descend',
    description: 'Three notes falling.',
    channelId: 'alerts-descend-v1',
    file: 'descend.wav',
    asset: '/sounds/descend.wav',
    icon: TrendDownIcon,
  },

  {
    value: 'dive',
    label: 'Dive',
    description: 'A tone sliding downwards.',
    channelId: 'alerts-dive-v1',
    file: 'dive.wav',
    asset: '/sounds/dive.wav',
    icon: CaretDoubleDownIcon,
  },

  {
    value: 'drone',
    label: 'Drone',
    description: 'A steady tone with a slow wobble.',
    channelId: 'alerts-drone-v1',
    file: 'drone.wav',
    asset: '/sounds/drone.wav',
    icon: WaveSineIcon,
  },

  {
    value: 'echo',
    label: 'Echo',
    description: 'A ping that repeats and fades.',
    channelId: 'alerts-echo-v1',
    file: 'echo.wav',
    asset: '/sounds/echo.wav',
    icon: RepeatIcon,
  },

  {
    value: 'glass',
    label: 'Glass',
    description: 'A high, glassy note.',
    channelId: 'alerts-glass-v1',
    file: 'glass.wav',
    asset: '/sounds/glass.wav',
    icon: SnowflakeIcon,
  },

  {
    value: 'heartbeat',
    label: 'Heartbeat',
    description: 'A low double thump.',
    channelId: 'alerts-heartbeat-v1',
    file: 'heartbeat.wav',
    asset: '/sounds/heartbeat.wav',
    icon: HeartbeatIcon,
  },


  {
    value: 'klaxon',
    label: 'Klaxon',
    description: 'A blunt horn. The hardest one to ignore.',
    channelId: 'alerts-klaxon-v1',
    file: 'klaxon.wav',
    asset: '/sounds/klaxon.wav',
    icon: MegaphoneIcon,
  },

  {
    value: 'ladder',
    label: 'Ladder',
    description: 'Four notes climbing upwards.',
    channelId: 'alerts-ladder-v1',
    file: 'ladder.wav',
    asset: '/sounds/ladder.wav',
    icon: StepsIcon,
  },

  {
    value: 'march',
    label: 'March',
    description: 'Low and high notes at a steady pace.',
    channelId: 'alerts-march-v1',
    file: 'march.wav',
    asset: '/sounds/march.wav',
    icon: MetronomeIcon,
  },


  {
    value: 'ping',
    label: 'Ping',
    description: 'One clear note that fades away.',
    channelId: 'alerts-ping-v1',
    file: 'ping.wav',
    asset: '/sounds/ping.wav',
    icon: SparkleIcon,
  },


  {
    value: 'pulse',
    label: 'Pulse',
    description: 'Quick even beeps.',
    channelId: 'alerts-pulse-v1',
    file: 'pulse.wav',
    asset: '/sounds/pulse.wav',
    icon: PulseIcon,
  },

  {
    value: 'radar',
    label: 'Radar',
    description: 'A slow sonar ping.',
    channelId: 'alerts-radar-v1',
    file: 'radar.wav',
    asset: '/sounds/radar.wav',
    icon: CrosshairIcon,
  },


  {
    value: 'siren',
    label: 'Siren',
    description: 'A slow wail up and down.',
    channelId: 'alerts-siren-v1',
    file: 'siren.wav',
    asset: '/sounds/siren.wav',
    icon: SirenIcon,
  },

  {
    value: 'spark',
    label: 'Spark',
    description: 'Short crackles.',
    channelId: 'alerts-spark-v1',
    file: 'spark.wav',
    asset: '/sounds/spark.wav',
    icon: FireIcon,
  },


  {
    value: 'strobe',
    label: 'Strobe',
    description: 'A burst of very fast ticks.',
    channelId: 'alerts-strobe-v1',
    file: 'strobe.wav',
    asset: '/sounds/strobe.wav',
    icon: LightningIcon,
  },


  {
    value: 'surge',
    label: 'Surge',
    description: 'A tone that rises and holds.',
    channelId: 'alerts-surge-v1',
    file: 'surge.wav',
    asset: '/sounds/surge.wav',
    icon: ChartLineUpIcon,
  },


  {
    value: 'sweep',
    label: 'Sweep',
    description: 'A tone sliding upwards.',
    channelId: 'alerts-sweep-v1',
    file: 'sweep.wav',
    asset: '/sounds/sweep.wav',
    icon: TrendUpIcon,
  },

  {
    value: 'tick',
    label: 'Tick',
    description: 'Soft clicks, like a clock.',
    channelId: 'alerts-tick-v1',
    file: 'tick.wav',
    asset: '/sounds/tick.wav',
    icon: TimerIcon,
  },


  {
    value: 'trill',
    label: 'Trill',
    description: 'Two high notes trading places quickly.',
    channelId: 'alerts-trill-v1',
    file: 'trill.wav',
    asset: '/sounds/trill.wav',
    icon: WaveSawtoothIcon,
  },


  {
    value: 'tritone',
    label: 'Tritone',
    description: 'Three notes rising, like an announcement.',
    channelId: 'alerts-tritone-v1',
    file: 'tritone.wav',
    asset: '/sounds/tritone.wav',
    icon: MusicNotesIcon,
  },


  {
    value: 'warble',
    label: 'Warble',
    description: 'A wobbling tone that will not sit still.',
    channelId: 'alerts-warble-v1',
    file: 'warble.wav',
    asset: '/sounds/warble.wav',
    icon: WaveTriangleIcon,
  },

  {
    value: 'whoop',
    label: 'Whoop',
    description: 'Three quick rising whoops.',
    channelId: 'alerts-whoop-v1',
    file: 'whoop.wav',
    asset: '/sounds/whoop.wav',
    icon: PoliceCarIcon,
  },
];

/**
 * How long each bundled tone runs, matching `scripts/build-alert-sounds.mjs`.
 *
 * Used to space repeats so one tone ends as the next begins. Kept here because the
 * value has to be known without reading the file, and it must be changed with the
 * generator's SUSTAIN_SECONDS.
 */
export const TONE_SECONDS = 12;

export const DEFAULT_SOUND: AlertSoundName = 'default';

export function soundFor(name: AlertSoundName) {
  return ALERT_SOUNDS.find((sound) => sound.value === name) ?? ALERT_SOUNDS[0];
}

export async function loadAlertSound(): Promise<AlertSoundName> {
  try {
    const stored = await storage.getItem(KEY);

    return ALERT_SOUNDS.some((sound) => sound.value === stored)
      ? (stored as AlertSoundName)
      : DEFAULT_SOUND;
  } catch {
    return DEFAULT_SOUND;
  }
}

export async function saveAlertSound(name: AlertSoundName): Promise<void> {
  try {
    await storage.setItem(KEY, name);
  } catch {
    // Falls back to the default next launch. Not worth interrupting anyone over.
  }
}
