-- Email becomes optional.
--
-- Not every operator has a work address, and requiring one meant inventing a fake to
-- get an account created. A username is the identity the system actually needs: it is
-- generated from the name when absent, and it is what the account signs in with.
--
-- The unique index stays and needs no change. Postgres treats nulls as distinct, so
-- any number of accounts can have no email while two cannot share one.
--
-- An account with no email signs in by username only, which is why the login field has
-- always accepted either.
alter table users alter column email drop not null;
