import * as SecureStore from 'expo-secure-store';
import type { IconProps } from 'phosphor-react-native';
import Alarm from 'phosphor-react-native/src/icons/Alarm';
import Bell from 'phosphor-react-native/src/icons/Bell';
import BellSimple from 'phosphor-react-native/src/icons/BellSimple';
import BellSimpleRinging from 'phosphor-react-native/src/icons/BellSimpleRinging';
import Bird from 'phosphor-react-native/src/icons/Bird';
import CaretDoubleDown from 'phosphor-react-native/src/icons/CaretDoubleDown';
import ChartLineUp from 'phosphor-react-native/src/icons/ChartLineUp';
import ChatsCircle from 'phosphor-react-native/src/icons/ChatsCircle';
import Crosshair from 'phosphor-react-native/src/icons/Crosshair';
import DotOutline from 'phosphor-react-native/src/icons/DotOutline';
import DotsThreeOutline from 'phosphor-react-native/src/icons/DotsThreeOutline';
import Fire from 'phosphor-react-native/src/icons/Fire';
import Heartbeat from 'phosphor-react-native/src/icons/Heartbeat';
import Lightning from 'phosphor-react-native/src/icons/Lightning';
import Megaphone from 'phosphor-react-native/src/icons/Megaphone';
import Metronome from 'phosphor-react-native/src/icons/Metronome';
import MusicNotes from 'phosphor-react-native/src/icons/MusicNotes';
import PoliceCar from 'phosphor-react-native/src/icons/PoliceCar';
import Pulse from 'phosphor-react-native/src/icons/Pulse';
import Repeat from 'phosphor-react-native/src/icons/Repeat';
import Siren from 'phosphor-react-native/src/icons/Siren';
import Snowflake from 'phosphor-react-native/src/icons/Snowflake';
import Sparkle from 'phosphor-react-native/src/icons/Sparkle';
import Steps from 'phosphor-react-native/src/icons/Steps';
import Timer from 'phosphor-react-native/src/icons/Timer';
import TrendDown from 'phosphor-react-native/src/icons/TrendDown';
import TrendUp from 'phosphor-react-native/src/icons/TrendUp';
import WaveSawtooth from 'phosphor-react-native/src/icons/WaveSawtooth';
import WaveSine from 'phosphor-react-native/src/icons/WaveSine';
import WaveSquare from 'phosphor-react-native/src/icons/WaveSquare';
import WaveTriangle from 'phosphor-react-native/src/icons/WaveTriangle';
import type { ComponentType } from 'react';

const KEY = 'dynavolt.alertSound';

export type AlertSoundName =
  | 'default'
  | 'chirp'
  | 'alarm'
  | 'beep'
  | 'sweep'
  | 'pulse'
  | 'siren'
  | 'warble'
  | 'ping'
  | 'tritone'
  | 'descend'
  | 'klaxon'
  | 'trill'
  | 'strobe'
  | 'bell'
  | 'surge'
  | 'blip'
  | 'buzzer'
  | 'chatter'
  | 'chime'
  | 'dive'
  | 'drone'
  | 'echo'
  | 'glass'
  | 'heartbeat'
  | 'ladder'
  | 'march'
  | 'radar'
  | 'spark'
  | 'tick'
  | 'whoop';

/**
 * The alert tones that ship inside the app.
 *
 * Bundled rather than picked at runtime, because that is the only kind of sound Android
 * will play for a notification while the app is closed. A channel's sound is copied
 * from the app's resources when the channel is created, so the file has to exist at
 * install time; a file chosen later cannot take its place.
 *
 * Generated by `scripts/build-alert-sounds.mjs`. They sit between roughly 1 and 3 kHz,
 * which is where a phone speaker is loudest and where a tone still carries across a
 * room with a transformer humming in it.
 *
 * Each one needs its own channel: Android freezes a channel's sound at creation, so
 * switching tones means switching channels rather than editing one.
 *
 * Listed alphabetically, with the device default pinned first: it is the "no chosen
 * tone" option rather than a tone, so it belongs at the top rather than filed under D.
 */
export const ALERT_SOUNDS: {
  value: AlertSoundName;
  label: string;
  description: string;
  /** The channel this tone plays through, or the shared default one. */
  channelId: string;
  /** The bundled file name, or null for Android's own notification sound. */
  file: string | null;
  /** The bundled asset, for previewing while the app is open. */
  asset: number | null;
  icon: ComponentType<IconProps>;
}[] = [
  {
    value: 'default',
    label: 'Device default',
    description: 'The notification sound your phone already uses.',
    channelId: 'alerts-v2',
    file: null,
    asset: null,
    icon: Bell,
  },


  {
    value: 'alarm',
    label: 'Alarm',
    description: 'Two tones back and forth, like an emergency vehicle.',
    channelId: 'alerts-alarm-v1',
    file: 'alarm.wav',
    asset: require('../../../assets/sounds/alarm.wav'),
    icon: Alarm,
  },


  {
    value: 'beep',
    label: 'Beep',
    description: 'Three plain high beeps.',
    channelId: 'alerts-beep-v1',
    file: 'beep.wav',
    asset: require('../../../assets/sounds/beep.wav'),
    icon: DotsThreeOutline,
  },


  {
    value: 'bell',
    label: 'Bell',
    description: 'A bell that rings out slowly.',
    channelId: 'alerts-bell-v1',
    file: 'bell.wav',
    asset: require('../../../assets/sounds/bell.wav'),
    icon: BellSimpleRinging,
  },

  {
    value: 'blip',
    label: 'Blip',
    description: 'A single quick tick.',
    channelId: 'alerts-blip-v1',
    file: 'blip.wav',
    asset: require('../../../assets/sounds/blip.wav'),
    icon: DotOutline,
  },

  {
    value: 'buzzer',
    label: 'Buzzer',
    description: 'A harsh low buzz.',
    channelId: 'alerts-buzzer-v1',
    file: 'buzzer.wav',
    asset: require('../../../assets/sounds/buzzer.wav'),
    icon: WaveSquare,
  },

  {
    value: 'chatter',
    label: 'Chatter',
    description: 'Fast little tones, one after another.',
    channelId: 'alerts-chatter-v1',
    file: 'chatter.wav',
    asset: require('../../../assets/sounds/chatter.wav'),
    icon: ChatsCircle,
  },

  {
    value: 'chime',
    label: 'Chime',
    description: 'Two notes, like a doorbell.',
    channelId: 'alerts-chime-v1',
    file: 'chime.wav',
    asset: require('../../../assets/sounds/chime.wav'),
    icon: BellSimple,
  },


  {
    value: 'chirp',
    label: 'Chirp',
    description: 'Two quick rising notes.',
    channelId: 'alerts-chirp-v1',
    file: 'chirp.wav',
    asset: require('../../../assets/sounds/chirp.wav'),
    icon: Bird,
  },


  {
    value: 'descend',
    label: 'Descend',
    description: 'Three notes falling.',
    channelId: 'alerts-descend-v1',
    file: 'descend.wav',
    asset: require('../../../assets/sounds/descend.wav'),
    icon: TrendDown,
  },

  {
    value: 'dive',
    label: 'Dive',
    description: 'A tone sliding downwards.',
    channelId: 'alerts-dive-v1',
    file: 'dive.wav',
    asset: require('../../../assets/sounds/dive.wav'),
    icon: CaretDoubleDown,
  },

  {
    value: 'drone',
    label: 'Drone',
    description: 'A steady tone with a slow wobble.',
    channelId: 'alerts-drone-v1',
    file: 'drone.wav',
    asset: require('../../../assets/sounds/drone.wav'),
    icon: WaveSine,
  },

  {
    value: 'echo',
    label: 'Echo',
    description: 'A ping that repeats and fades.',
    channelId: 'alerts-echo-v1',
    file: 'echo.wav',
    asset: require('../../../assets/sounds/echo.wav'),
    icon: Repeat,
  },

  {
    value: 'glass',
    label: 'Glass',
    description: 'A high, glassy note.',
    channelId: 'alerts-glass-v1',
    file: 'glass.wav',
    asset: require('../../../assets/sounds/glass.wav'),
    icon: Snowflake,
  },

  {
    value: 'heartbeat',
    label: 'Heartbeat',
    description: 'A low double thump.',
    channelId: 'alerts-heartbeat-v1',
    file: 'heartbeat.wav',
    asset: require('../../../assets/sounds/heartbeat.wav'),
    icon: Heartbeat,
  },


  {
    value: 'klaxon',
    label: 'Klaxon',
    description: 'A blunt horn. The hardest one to ignore.',
    channelId: 'alerts-klaxon-v1',
    file: 'klaxon.wav',
    asset: require('../../../assets/sounds/klaxon.wav'),
    icon: Megaphone,
  },

  {
    value: 'ladder',
    label: 'Ladder',
    description: 'Four notes climbing upwards.',
    channelId: 'alerts-ladder-v1',
    file: 'ladder.wav',
    asset: require('../../../assets/sounds/ladder.wav'),
    icon: Steps,
  },

  {
    value: 'march',
    label: 'March',
    description: 'Low and high notes at a steady pace.',
    channelId: 'alerts-march-v1',
    file: 'march.wav',
    asset: require('../../../assets/sounds/march.wav'),
    icon: Metronome,
  },


  {
    value: 'ping',
    label: 'Ping',
    description: 'One clear note that fades away.',
    channelId: 'alerts-ping-v1',
    file: 'ping.wav',
    asset: require('../../../assets/sounds/ping.wav'),
    icon: Sparkle,
  },


  {
    value: 'pulse',
    label: 'Pulse',
    description: 'Quick even beeps.',
    channelId: 'alerts-pulse-v1',
    file: 'pulse.wav',
    asset: require('../../../assets/sounds/pulse.wav'),
    icon: Pulse,
  },

  {
    value: 'radar',
    label: 'Radar',
    description: 'A slow sonar ping.',
    channelId: 'alerts-radar-v1',
    file: 'radar.wav',
    asset: require('../../../assets/sounds/radar.wav'),
    icon: Crosshair,
  },


  {
    value: 'siren',
    label: 'Siren',
    description: 'A slow wail up and down.',
    channelId: 'alerts-siren-v1',
    file: 'siren.wav',
    asset: require('../../../assets/sounds/siren.wav'),
    icon: Siren,
  },

  {
    value: 'spark',
    label: 'Spark',
    description: 'Short crackles.',
    channelId: 'alerts-spark-v1',
    file: 'spark.wav',
    asset: require('../../../assets/sounds/spark.wav'),
    icon: Fire,
  },


  {
    value: 'strobe',
    label: 'Strobe',
    description: 'A burst of very fast ticks.',
    channelId: 'alerts-strobe-v1',
    file: 'strobe.wav',
    asset: require('../../../assets/sounds/strobe.wav'),
    icon: Lightning,
  },


  {
    value: 'surge',
    label: 'Surge',
    description: 'A tone that rises and holds.',
    channelId: 'alerts-surge-v1',
    file: 'surge.wav',
    asset: require('../../../assets/sounds/surge.wav'),
    icon: ChartLineUp,
  },


  {
    value: 'sweep',
    label: 'Sweep',
    description: 'A tone sliding upwards.',
    channelId: 'alerts-sweep-v1',
    file: 'sweep.wav',
    asset: require('../../../assets/sounds/sweep.wav'),
    icon: TrendUp,
  },

  {
    value: 'tick',
    label: 'Tick',
    description: 'Soft clicks, like a clock.',
    channelId: 'alerts-tick-v1',
    file: 'tick.wav',
    asset: require('../../../assets/sounds/tick.wav'),
    icon: Timer,
  },


  {
    value: 'trill',
    label: 'Trill',
    description: 'Two high notes trading places quickly.',
    channelId: 'alerts-trill-v1',
    file: 'trill.wav',
    asset: require('../../../assets/sounds/trill.wav'),
    icon: WaveSawtooth,
  },


  {
    value: 'tritone',
    label: 'Tritone',
    description: 'Three notes rising, like an announcement.',
    channelId: 'alerts-tritone-v1',
    file: 'tritone.wav',
    asset: require('../../../assets/sounds/tritone.wav'),
    icon: MusicNotes,
  },


  {
    value: 'warble',
    label: 'Warble',
    description: 'A wobbling tone that will not sit still.',
    channelId: 'alerts-warble-v1',
    file: 'warble.wav',
    asset: require('../../../assets/sounds/warble.wav'),
    icon: WaveTriangle,
  },

  {
    value: 'whoop',
    label: 'Whoop',
    description: 'Three quick rising whoops.',
    channelId: 'alerts-whoop-v1',
    file: 'whoop.wav',
    asset: require('../../../assets/sounds/whoop.wav'),
    icon: PoliceCar,
  },
];

export const DEFAULT_SOUND: AlertSoundName = 'default';

export function soundFor(name: AlertSoundName) {
  return ALERT_SOUNDS.find((sound) => sound.value === name) ?? ALERT_SOUNDS[0];
}

export async function loadAlertSound(): Promise<AlertSoundName> {
  try {
    const stored = await SecureStore.getItemAsync(KEY);

    return ALERT_SOUNDS.some((sound) => sound.value === stored)
      ? (stored as AlertSoundName)
      : DEFAULT_SOUND;
  } catch {
    return DEFAULT_SOUND;
  }
}

export async function saveAlertSound(name: AlertSoundName): Promise<void> {
  try {
    await SecureStore.setItemAsync(KEY, name);
  } catch {
    // Falls back to the default next launch. Not worth interrupting anyone over.
  }
}
